version: '2.4'
services:
    # The ERP Container
    # -----------------
    # Accessing the Container: docker exec -u erp -it erp-train bash
    #
    erp-train:
#      image: abasartifactory.jfrog.io/partner/abas/test:${ERP_VERSION:-v2019r4}
      image: abasartifactory.jfrog.io/partner/abas/neumand:${ERP_VERSION:-v2100r8}
      init: true
      container_name: "erp-train"

      ports:
      - "2214:22"
      - "8010:80"
      - "6569:6550"
      - "48601:48392"
#      - "5005:5005"

      environment:
      - http_proxy
      - https_proxy
      - no_proxy

      # The hostname is very important, especially if you intend to use `docker commit`
      user: s3
      hostname: dockerbau
      command: /abas/bin/starteVersion.sh run

      mem_limit: 4g
      healthcheck:
        test: netstat -ltn | grep -c 18056
        interval: 5s
        timeout: 5s
        retries: 10
        start_period: 5s
