version: '2.3'
services:
    # The ERP Container
    # -----------------
    # Accessing the Container: docker exec -u erp -it erp-train bash
    #
    erp-train:
      build:
        context: .
        dockerfile: Dockerfile-erp-overrides
        args:
          - ERP_VERSION=${ERP_VERSION:-2017r4n16p39}
      init: true
      container_name: "erp-train"

      ports:
      - "2214:22"
      - "8010:80"
      - "6569:6550"
      - "48601:48392"
      - "5005:5005"

      environment:
      - http_proxy
      - https_proxy
      - no_proxy

      # The hostname is very important, especially if you intend to use `docker commit`
      user: s3
      hostname: dockerbau
      command: ["sh", "-c", "cd /abas/erp && eval $$(sh denv.sh) && datmeta -s && echo success && pwd && ${RUNCOMMAND_PATH:-/abas/bin/}starteVersion.sh run"]

  # The Nexus Container
    nexus-train:
      image: sonatype/nexus:oss
      container_name: "nexus-train"
      ports:
      - "8090:8081"
