== Installation

The Training App is a marketplace app and subject of licensing. It is licensed for all current Docker images available
in the abas Partner Docker Registry.

If you want to try it out in any other client you can contact us and we will give you a free license for this app,
since it is for demonstration purposes.

In order to install it you need to have a hybrid tenant configured. Follow the instructions for link::https://documentation.abas.cloud/en/cloud-connect/[abas Cloud Connect]
to setup a hybrid tenant.

Once you have your hybrid tenant up and running you can install the app via the link::https://documentation.abas.cloud/en/esdk/#abas-app-installer[abas App Installer].
In the abas client you want to install the Training App in run the following command:

[source,shell,subs="verbatim,attributes"]
----
abas-app-installer -a https://s3.amazonaws.com/abas-app-releases/train/{productVersion}/trainingApp-{productVersion}-app.jar
----

You can also install the Training App using the ESDK Gradle Plugin.

To do so execute the following commands:

[source,shell]
----
docker-compose up -d
./initGradleProperties
./gradlew checkPreconditions
----

This will make sure your infrastructure is configured correctly and up and running.

[source,shell]
----
./gradlew fullInstall
----
